### ISSUE TITLE
"ReferenceError document is not defined" - SSR problem in Nuxt.js?

### ISSUE THREAD

**Issue by emdahlstrom** [bkzl/vue-float-label#22]
Hi!
I'm trying to use this amazing component in Nuxt but am running into problems with what I think is SSR and Nuxt trying to run the component on the server side where "document" isn't available. Looking at the code I wonder if it is the style injection that is causing the problems. 

I have tried to write a Nuxt plugin to load it with ssr=false but I'm probably messing it up. Any help in writing a working Nuxt plugin (would be useful for other users as well?) and using that would be much appreciated, or in the long term seeing how the component could be made ssr safe (the most versatile solution). I would love to help if I can. I tried to have a go at the component code but got confused when the dist code seemed different than the prettified source - can't seem to find the style injection anywhere else for example. 

Here is the output:
```
[vue-router] Failed to resolve async component default: ReferenceError: document is not defined
[vue-router] uncaught error during route navigation:
ReferenceError: document is not defined
    at s (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:5259)
    at r (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:5081)
    at e.exports (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:6702)
    at Object.l (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:4745)
    at t (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:330)
    at Object.defineProperty.value (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:740)
    at t (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:330)
    at Object.<anonymous> (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:2761)
    at t (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:330)
    at /Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:713
    at /Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:722
    at n (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:81)
    at Object.<anonymous> (/Users/em/Code/vuenuxt/node_modules/vue-float-label/dist/vue-float-label.js:1:207)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at r (/Users/em/Code/vuenuxt/node_modules/vue-server-renderer/build.js:7758:16)
    at Object.<anonymous> (server-bundle.js:4188:18)
```

**Comment by emdahlstrom** [comment]
Hi! Managed to get it running as a nuxt plugin with ssr false - to only load it on the client side to avoid the ssr problem.

In nuxt.config.js
```
module.exports = {
...
  plugins: [
    { src: '~plugins/vue-float-label.js', ssr: false }
  ],
...
}
```

In ~plugins/vue-float-label.js
```
// This code will be injected before initializing the root App
import Vue from 'vue'
import VueFloatLabel from 'vue-float-label'

// Activate plugin
Vue.use(VueFloatLabel)
```

My mistake was also importing VueFLoatLabel in the nuxt page component which meant it was still being run at the server side. **It's enough to import it as a plugin in nuxt.config.js and then just using the component in the template markup.** 

I would assume that this solution messes up server side rendering quite a bit so it would be better to make the component itself ssr safe.
